tree_builder_failure_stops_the_run

diff --git a/.terrateam/config.yml b/.terrateam/config.yml
--- a/.terrateam/config.yml
+++ b/.terrateam/config.yml
@@ -1,13 +1,18 @@
 tree_builder:
   enabled: true
-  script: '${TERRATEAM_ROOT}/bin/generate build-tree'
+  script: '#! /usr/bin/env bash
 
+    echo "On purpose failed tree run" >&2
+
+    exit 1
+
+    '
 config_builder:
   enabled: true
-  script: '${TERRATEAM_ROOT}/bin/generate build-config'
+  script: '#! /usr/bin/env bash
 
-hooks:
-  all:
-    pre:
-      - type: run
-        cmd: ['${TERRATEAM_ROOT}/bin/generate', 'build']
+    echo ''{"engine": {"name": "tofu"}}''
+
+    '
+engine:
+  name: tofu
